### PR TITLE
Save and restore main window pos on startup

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by TingPing** [comment]
The patch seems fine but I'm not sure it makes sense to add this. For Wayland users this does nothing. If this ever moves to GTK4 it has to be removed anyway.

To quote the [GTK docs](https://docs.gtk.org/gtk3/method.Window.get_position.html):

> In practice, saving the window position should not be left to applications, as they lack enough knowledge of the windowing system and the window manager state to effectively do so. The appropriate way to implement saving the window position is to use a platform-specific protocol, wherever that is available.

**Comment by luk1337** [comment]
> The patch seems fine but I'm not sure it makes sense to add this. For Wayland users this does nothing. If this ever moves to GTK4 it has to be removed anyway.
> 
> To quote the [GTK docs](https://docs.gtk.org/gtk3/method.Window.get_position.html):
> 
> > In practice, saving the window position should not be left to applications, as they lack enough knowledge of the windowing system and the window manager state to effectively do so. The appropriate way to implement saving the window position is to use a platform-specific protocol, wherever that is available.

hmm, is there a proper way to do it then?

**Comment by luk1337** [comment]
> > The patch seems fine but I'm not sure it makes sense to add this. For Wayland users this does nothing. If this ever moves to GTK4 it has to be removed anyway.
> > To quote the [GTK docs](https://docs.gtk.org/gtk3/method.Window.get_position.html):
> > > In practice, saving the window position should not be left to applications, as they lack enough knowledge of the windowing system and the window manager state to effectively do so. The appropriate way to implement saving the window position is to use a platform-specific protocol, wherever that is available.
> 
> hmm, is there a proper way to do it then?

this seems to work for me:
image

**Comment by LaserEyess** [comment]
> hmm, is there a proper way to do it then?

I see you already figured it out, but on Wayland specifically there is [this protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/18) which should give clients the ability to negotiate this with compositors. 

As for the idea overall, I agree with TingPing, this isn't a solution that will last. I still want to try and port this to gtk4 at some point, but it require some pretty substantial rewrites, and adding code that will eventually have to be removed is not the best idea.

**Pull request closed without merging**
