### PR TITLE
build: Add -Wno-typedef-redefinition

### PR DESCRIPTION
**Pull request by TingPing**
This is going to happen anywhere glib macros are used and isn't really a problem.

### CODE REVIEW

**Comment by TingPing** [comment]
Just checking if the macOS build is warning free now.

**Comment by LaserEyess** [comment]
Oops, thanks for fixing this!

**Comment by TingPing** [comment]
There is one warning left:

```
 ../src/trg-general-panel.c:256:85: warning: format string is empty [-Wformat-zero-length]
        gchar *keyMarkup = g_markup_printf_escaped(strlen(key) > 0 ? "<b>%s:</b>" : "", key);
                                                                                    ^~
```

Not sure its a real problem or not. But we could just do a `g_strdup()` instead of a format.

**Comment by LaserEyess** [comment]
```C
char *keyMarkup = g_markup_printf_escaped(strlen(key) > 0 ? "<b>%s:</b>" : " ", key);
```

¯\\_(ツ)_/¯

**Comment by TingPing** [comment]
I was thinking:

```c
char *keyMarkup = strlen(key) == 0 ? g_strdup ("") : g_markup_printf_escaped("<b>%s:</b>", key);
```

**Comment by LaserEyess** [comment]
your is likely more proper, yeah.

**Comment by TingPing** [comment]
Fixed in 755ca5c75acc63680dc0f71601e5ed7022463001

Turns out `strlen(key) == 0` was impossible...

**Pull request merged**
